version: '3'
services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app
